apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-express-config
data:
  config.js: |
    module.exports = {
      mongodb: {
        server: process.env.ME_CONFIG_MONGODB_SERVER,
        port: process.env.ME_CONFIG_MONGODB_PORT || 27017,
        auth: [
          {
            database: "admin",
            username: process.env.ME_CONFIG_MONGODB_ADMINUSERNAME,
            password: process.env.ME_CONFIG_MONGODB_ADMINPASSWORD
          }
        ]
      },
      site: {
        baseUrl: '/',
        cookieSecret: 'cookiesecret',
        sessionSecret: 'sessionsecret'
      },
      siteName: '📊 My Database Dashboard',
      basicAuth: {
        username: process.env.ME_CONFIG_BASICAUTH_USER,
        password: process.env.ME_CONFIG_BASICAUTH_PASSWORD
      }
    };